#!/usr/bin/env escript
%%! -smp enable -pa ebin -pa deps/*/ebin
main([]) ->
  ok = application:start(crypto),
  ok = application:start(asn1),
  ok = application:start(public_key),
  ok = application:start(ssl),
  ok = application:start(cowlib),
  ok = application:start(ranch),
  ok = application:start(cowboy),
  ok = application:start(gun),

  Dispatch = cowboy_router:compile([
    {'_', [
      {"/api/[...]", ranger_example, []},
      {"/:app/[...]", ranger_example, []},
      {"/", ranger_example, []}
    ]}
  ]),

  {ok, _} = cowboy:start_http(http, 100, [{port, 8080}], [
    {env, [{dispatch, Dispatch}]}
  ]),

  ok.
